[package]
name = "algorithms-2-2021"
version = "0.1.0"
authors = ["Yacob (Kobi) Cohen-Arazi <kobi.cohenarazi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
